### PR TITLE
Merge main -> RBC

### PR DESCRIPTION
**Pull request by rupertnash**
OK! This is 90% done.

TODO:
- [x]  Copyright statements
- [ ]  SimMaster/Traits/ Top level defines in CMake
- [x]  LB vs lattice in XML units
- [x]  RheologyModelTests/TruncatedPowerLaw fail
- [x]  Vector3D operator< WTF?
- [x]  missing resources: unittests/resources/P6_190514_x63x0.6_0_RED_BW_corrected_tubed_smoothed_*
- [x] Remove util/unique
- [ ] Test on real RBC problems
- [x] Move cppunit unit tests to Catch2
- [x] Remove cppunit again

### CODE REVIEW

**Comment by mobernabeu** [comment]
Thanks a lot @rupertnash, things that stand out from the list:
 * RheologyModelTests/TruncatedPowerLaw fail refers to #388. 
 * The missing resources are for "tests" that are more functional than unit tests and need to go (they are too long)
 * What do you have in mind as "real RBC problems", something like the diffTest?

I'll start making my way through these 3 points next week. For everything else I'm happy for you to make a call.

**Comment by otbrown** [comment]
>  Vector3D operator< WTF?

My instinct would be `return getMagnitudeSquared() < anotherVector.getMagnitudeSquared()`. Is there a reason for the lexicographical comparison?

**Comment by rupertnash** [comment]
Vectors are not ordered; the presence of this overload is a crime against maths. I suspect it is there to allow the vectors to be used as a key in `std::map` or `std::set` but haven't had a chance to look.

**Comment by otbrown** [comment]
Well it compiles and no new tests fail with that change, is it likely there's a more subtle issue, or shall I push it?

**Comment by rupertnash** [comment]
> Well it compiles and no new tests fail with that change, is it likely there's a more subtle issue, or shall I push it?

You've pushed already? We're not yet ready to merge, I reckon.

**Comment by otbrown** [comment]
I hadn't, that was a change to vtk/find_or_build.cmake which I came across while trying to build with `HEMELB_BUILD_RBC` -- I'm having further issues there with HDF5, which I'll need to dig in to. 

You're right, definitely not ready to merge -- I have however (now) pushed the Vector3D operator< change to this branch.

**Comment by rupertnash** [comment]
🤢Please force push back as it was

**Comment by rupertnash** [comment]
Regarding "LB" vs "lattice" for unit names in the XML files. For sanity/consistency I'd like to use only one term. The use of "lattice" predates "LB" and is used in more parts of the code. "LB" is used only by the RBCs.

By the power granted above I've picked "lattice": @mobernabeu I know this will mean you need to tweak your input files - sorry.

**Comment by mobernabeu** [comment]
I accept responsibility for the Vector3D operator< horror and applaud the solution in 
f8c3e15!

**Comment by rupertnash** [comment]
FYI, I've almost fixed #388  - will prob have to bump the xml version number

**Comment by otbrown** [comment]
@rupertnash happy new year! I come bearing a request for updates from Timm -- how is this going? Any setbacks, and anything I can help with?

**Comment by rupertnash** [comment]
Hi! I've done a few bits: see PRs #757 and #758 which resolve some of the issues

Right now I'm trying to get some CI going.

You could:
- start moving some unit tests from cppunit to catch2? (only move passing ones for now) (and beware the in flight PRs - not sure if @mobernabeu wants to get eyes on them first)
- think how we are going to move the parallel unit tests over to catch

**Comment by rupertnash** [comment]
Descoping:
- SimMaster/Traits/ Top level defines in CMake (will deal with as part of eCSE project)
- Test on real RBC problems

**Comment by rupertnash** [comment]
Hi @mobernabeu - I think we can merge this and then merge to main if you're happy. However please don't merge with the button as GH seems upset with it, so I'll merge from command line.

**Comment by mobernabeu** [comment]
Amazing job @rupertnash. Go for it!

**Pull request merged**
