### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by rupertnash**
Python 2 is dead. It is an ex-implementation, it has ceased to be, etc....

We really need to start supporting python 3 and I've arbitrarily picked 3.7 (released June 2018) as a new minimum version.

I am very happy to change this in response to requirements and indeed in this PR so far, I'm maintaining compatibility with 2.7 via `six`

### CODE REVIEW

**Review by mobernabeu — APPROVED** [review]
Looking good! Great to remove support fo ancient VTK and adding tests to CI.

I was helping Ellie to get the setuptool running in Python3 and looks like `Tools/setuptool/setup.py` hasn't been ported yet. Is that in the list of things to do?

As a separate ticket: I would suggest dropping the "snapshots" feature and stop maintaining that code. Thoughts?

**Comment by rupertnash** [comment]
Setuptool is on the list. Agree about the snapshots. Any views about dropping py2?

**Comment by mobernabeu** [comment]
I would say drop it. It's been a while since VTK/VMTK run on python3.

@seedel please keep an eye on this PR, once it's merged we can finish installing the setup tool on your laptop.

**Comment by mobernabeu** [comment]
Sorry about sloppy English before. I should've said that it's been a while since VTK/VMTK was ported to python3.

@seedel needs to run the setuptool on python3 soonish. Is this something you could give us a hand with this week? No worries if not! Just let me know so I can plan.

**Comment by rupertnash** [comment]
OK - I'll have a look at this now

**Comment by rupertnash** [comment]
I just want to get this running with the diffTest in CI then I think we can merge

**Pull request merged**
